services:
  db:
    image: postgres:16
    container_name: snippetbox-db
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_USER: snippetbox_user
      POSTGRES_PASSWORD: securepassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  pgdata:
